# yaml-language-server: $schema=https://raw.githubusercontent.com/chri11g6/sops-schema/refs/heads/master/sops.schema.json
creation_rules:
  - age: >-
      age13zlejryr25ml24w0phukreks7f3283n07z20mcm82mp0l87xxq7syka0rs
